#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# unload the old theme
if [ -f "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down
	rm /tmp/leftwm-theme-down
fi


#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpeg
fi
# load the down script to the expected location
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# enable xmobar
# if [ -x "$(command -v xmobar)" ]; then
# 	xmobar &> /dev/null &
# fi


# enable polybar
if [ -x "$(command -v polybar)" ]; then
	polybar &> /dev/null &
fi

# set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# # load polybar
# polybar -c $SCRIPTPATH/polybar.ini &> /dev/null &

# # load picom (note: cannot set daemon command from config file)
# picom --daemon --config $SCRIPTPATH/picom.conf
