#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# unload the old theme
if [ -f "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down
	rm /tmp/leftwm-theme-down
fi

# load the down script to the expected location
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# enable xmobar
if [ -x "$(command -v xmobar)" ] && [ -f "$HOME/.fehbg" ]; then
	xmobar &> /dev/null &
fi

# # load polybar
# polybar -c $SCRIPTPATH/polybar.ini &> /dev/null &

# # load picom (note: cannot set daemon command from config file)
# picom --daemon --config $SCRIPTPATH/picom.conf
